Feat/#99 seen page
RookieFit/Front-old pull request #118
Opened 2024-12-02 01:18 UTC by aeaesi

일단 올려봐요 오류 있는거 말해주시면 고칠게요

2024-12-02 02:16 UTC, dahli4 requested changes
수정사항 확인해주세유

2024-12-02 02:16 UTC, dahli4 commented on rookiefit/src/mypage/myPage/topBox/topMainBox/topMainBox.tsx
> +               <InformationMiniBox role={'trainer'} value={false} />
위에 같이 넣으면 어떨까요? 트레이너일때 조건은 똑같은거 같은데

2024-12-02 02:16 UTC, dahli4 commented on rookiefit/src/mypage/myPage/topBox/topMainBox/topMainBoxEdit.tsx
> +            <InformationMiniBoxEdit role={'user'} value={false} />
여기 한칸 띄워쓰기 지워주시고 위에랑 같이 합쳐보는건 어떨까요?

2024-12-02 02:16 UTC, dahli4 commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeedcommunityComponents/seenFeedGridPhoto.tsx
> +            <ImageUploader onImageUpload={function (image: File | null): void {
여기 이미지를 출력하는 곳 아닌가용? 이미지 업로더는 이미지를 올리기 위한건데 여기에 쓰는건 맞지 않다고 생각해요

2024-12-02 02:16 UTC, dahli4 commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeed.tsx
> +          <SeenFeedGridPhoto />
이건 왜 세개나 들어가있나용?

2024-12-02 02:16 UTC, dahli4 commented on rookiefit/src/mypage/seenPage/seenProfile/seenProfile.css
> +    border: thin solid  rgb(153, 151, 151);
rgb앞에 공백 지워주세유

2024-12-02 02:16 UTC, dahli4 commented on rookiefit/src/mypage/seenPage/seenProfile/seenProfile.tsx
> +  const marketChatPage = () => {
트레이너에서 채팅기능은 빠지지 않았나요?

2024-12-02 05:00 UTC, aeaesi commented on rookiefit/src/mypage/myPage/topBox/topMainBox/topMainBox.tsx
> +               <InformationMiniBox role={'trainer'} value={false} />
합쳤습니다

2024-12-02 05:02 UTC, aeaesi commented on rookiefit/src/mypage/myPage/topBox/topMainBox/topMainBoxEdit.tsx
> +            <InformationMiniBoxEdit role={'user'} value={false} />
고쳤습니다

2024-12-02 05:04 UTC, aeaesi commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeed.tsx
> +          <SeenFeedGridPhoto />
한 줄에 3개씩 나열시키고 싶어서 넣어봤습니다. 수정하겠습니다

2024-12-02 05:05 UTC, aeaesi commented on rookiefit/src/mypage/seenPage/seenProfile/seenProfile.css
> +    border: thin solid  rgb(153, 151, 151);
완

2024-12-02 05:09 UTC, aeaesi commented on rookiefit/src/mypage/seenPage/seenProfile/seenProfile.tsx
> +  const marketChatPage = () => {
맞네요 그럼 편집하기로 바꿀게요

2024-12-02 05:25 UTC, aeaesi commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeedcommunityComponents/seenFeedGridPhoto.tsx
> +            <ImageUploader onImageUpload={function (image: File | null): void {
여기서 올리고 출력까지 하려는데 어떻게 짜야 할지 모으겠어요...

일반 유저는 9개까지 보이고 트레이너는 3개에 스크롤 기능까지 넣을까 생각중인데... 흠

2024-12-02 05:28 UTC, parangstar commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeedcommunityComponents/seenFeedGridPhoto.tsx
> +            <ImageUploader onImageUpload={function (image: File | null): void {
게시물에 올라간 사진 띄워주는거 아니었나요? 허걱

2024-12-02 05:59 UTC, aeaesi commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeed.tsx
> +          <SeenFeedGridPhoto />
SeenFeedGridPhoto 자체에서 갯수 정하게 바꿨습니다.

2024-12-02 06:01 UTC, aeaesi commented
일단 바꿨습니다. 사진 관련 것들은 더 만져야 해서 하고 있겠습니다.

2024-12-02 06:46 UTC, dahli4 requested changes

2024-12-02 06:46 UTC, dahli4 commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeedcommunityComponents/seenFeedGridPhoto.tsx
> +                        onImageUpload={(image: File | null) => {
이미지 업로드 이거는 안쓸거아 업로더매니로 바꿔주세욧

2024-12-02 07:44 UTC, aeaesi commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeedcommunityComponents/seenFeedGridPhoto.tsx
> +                        onImageUpload={(image: File | null) => {
이게 한 칸 한 칸 따로따로 업로드 되게 하고 싶어서 썼는데 혹시 별론가요?

2024-12-02 08:12 UTC, dahli4 commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeedcommunityComponents/seenFeedGridPhoto.tsx
> +                        onImageUpload={(image: File | null) => {
이미지업로더매니로 하나씩 올리면 될거같은데 이미지업로더는 하나만 올리는기능이라 중복되서 지울려구여

2024-12-02 09:08 UTC, aeaesi commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeedcommunityComponents/seenFeedGridPhoto.tsx
> +                        onImageUpload={(image: File | null) => {
그 매니는 한 칸 한 칸 눌러 올리는게 아니고 다시 짜보께요

2024-12-02 09:44 UTC, parangstar commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeedcommunityComponents/seenFeedGridPhoto.tsx
> +                        onImageUpload={(image: File | null) => {
게시물에 올라간 사진 띄워주는거 아니었나요? 허걱

2024-12-02 09:44 UTC, parangstar commented
게시물에 올라간 사진 띄워주는거 아니었나요? 허걱

2024-12-02 09:45 UTC, parangstar commented
글고 마이페이지에 상단으로 올라가는 버튼 추가해주세요 제가 만들어 놓은거 땡겨 쓰시면 대요

2024-12-04 01:31 UTC, dahli4 approved these changes
확인했습니다

2024-12-04 01:31 UTC, dahli4 commented on rookiefit/src/mypage/myPage/bottomBox/graphBoxEdit.tsx
혹시 차트도 편집이 가능한건가요? 이제보니 그래프박스에딧과 그냥 그래프박스의 차이가 없는거같은데...

2024-12-04 01:32 UTC, merged