[Feat] #131 작업본 1차
RookieFit/Front-old pull request #134
Opened 2024-12-04 10:56 UTC by aeaesi

1차 작업본

2024-12-04 11:19 UTC, dahli4 requested changes

2024-12-04 11:19 UTC, dahli4 commented on rookiefit/src/mypage/myPage/topBox/informationBox/informationMiniBox/informationMiniBox.tsx
> +  const [isUserNickName, setIsUserNickName] = useState(information.usernickname);
음 이 부분을 객체로 만들어서 관리하면 좀 더 깔끔하게 보일거같은데 한번 찾아보고 적용해봐도 좋을거같아욜

2024-12-05 02:57 UTC, aeaesi commented on rookiefit/src/mypage/myPage/topBox/informationBox/informationMiniBox/informationMiniBox.tsx
> +  const [isUserNickName, setIsUserNickName] = useState(information.usernickname);
완

2024-12-05 03:44 UTC, dahli4 requested changes

2024-12-05 03:44 UTC, dahli4 commented on rookiefit/src/mypage/myPage/topBox/informationBox/informationMiniBox/informationMiniBox.tsx
> +  const updateInfo = (setFunction) => (field: any, value: any) => {
타입을 정확히 적어주시면 좋을거같아용

2024-12-05 03:44 UTC, dahli4 commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeedcommunityComponents/seenFeedGridBox.tsx
> +    })
들여쓰기가 좀 이상하네요 아랫줄이랑 같이 한칸 밀어주세요

2024-12-05 03:45 UTC, aeaesi commented on rookiefit/src/mypage/myPage/topBox/informationBox/informationMiniBox/informationMiniBox.tsx
> +  const updateInfo = (setFunction) => (field: any, value: any) => {
완

2024-12-05 03:55 UTC, aeaesi commented on rookiefit/src/mypage/seenPage/seenFeed/seenFeedcommunityComponents/seenFeedGridBox.tsx
> +    })
완 tab 2칸인 것들 전부 4칸으로 바꿨습니다

2024-12-05 09:06 UTC, dahli4 approved these changes

2024-12-05 09:26 UTC, merged